//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;

using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace T4_Toolbox_Experiements
{
	[TestClass]
	public class Controller1_Action1Tests : InMemoryHosting
	{

		[TestMethod]
		public void HPath1()
		{
		}

		[TestMethod]
		public void HPath2()
		{
		}

		[TestMethod]
		public void EPath1()
		{
		}

		[TestMethod]
		public void EPath2()
		{
		}
	}
}
