


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4_Toolbox_Experiements
{
	public class ControllerActionTests : InMemoryHosting
	{
		[TestMethod]
		public void ThisShouldWork()
		{
			Console.Writeln("Hello");
		}
	}
}


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4_Toolbox_Experiements
{
	public class ControllerActionTests2 : InMemoryHosting
	{
		[TestMethod]
		public void ThisShouldWork()
		{
			Console.Writeln("Hello");
		}
	}
}


